name: Process Requirements

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-profiles:
    name: Process Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install fhirscripts
        run: pipx install -f git+https://github.com/gematik/fhir-scripts.git

      - name: Install igtools
        run: fhirscripts install --igtools

      - name: Process requirements
        run: fhirscripts build defs --only-req

      - name: Push changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.${INPUT_ORGANIZATION_DOMAIN}"
            git add .
            git commit -m "ðŸ“‹ re-generate"
            git fetch -p
            git rebase origin/${GITHUB_REF}
            git push origin ${GITHUB_REF}
          fi
        shell: bash
